name: flyway

services:
  flyway:
    image: flyway/flyway:10
    command: -url=$DB_URL -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD migrate
    volumes:
      - ../../flyway/sql:/flyway/sql
      - ../../flyway/conf:/flyway/conf
    restart: no
