name: open-asset-allocator-base

services:
  backend:
    env_file: .env
    environment:
      - PORT=8080
      - WEB_STATIC_SOURCE_REL_PATH=/websrc
      - ROOT_HTML_FILENAME=root.html
    depends_on:
      db:
        condition: service_healthy
      migration-engine:
        condition: service_completed_successfully

  #TODO: create local image with init script inside for build
  db:
    image: postgres:17.4-bullseye
    restart: always
    env_file: .env
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ../postgres/initdb-scripts/:/docker-entrypoint-initdb.d/

  migration-engine:
    extends:
      file: flyway/docker-compose-flyway.yml
      service: flyway
    depends_on:
      db:
        condition: service_healthy
