name: open-asset-allocator-base

services:
  db:
    image: postgres:16.3-bullseye
    restart: always
    env_file: .env
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

  migration-engine:
    extends:
      file: flyway/docker-compose-flyway.yml
      service: flyway
    depends_on:
      db:
        condition: service_healthy
