name: open-asset-allocator-dev

services:
  backend:
    extends:
      file: docker-compose-base.yml
      service: backend
    build:
        context: .
        dockerfile: ./backend/Dockerfile
        target: dev
    # working_dir value has to be the same of mapped volume
    working_dir: /project-package
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ../go/:/project-package/

  db:
    extends:
      file: docker-compose-base.yml
      service: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration-engine:
    extends:
      file: docker-compose-base.yml
      service: migration-engine

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DEV_DATA_DIR}