name: open-asset-allocator-dev

include:
  - docker-compose-base.yml

services:
  backend:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    environment:
      - PORT=8080
      - WEB_STATIC_CONTENT_PATH=not-used
      - WEB_STATIC_COMPONENTS_PATH=not-used
      - ROOT_HTML_FILENAME=not-used
    working_dir: /project-package
    ports:
      - "8080:8080"
    volumes:
      - ../go/:/project-package/
    depends_on:
      db:
        condition: service_healthy
      migration-engine:
        condition: service_completed_successfully