package util

import (
	"reflect"
)

func ToPointerSlice[S any](slice []S) []*S {
	result := make([]*S, len(slice))
	for index, value := range slice {
		result[index] = &value
	}
	return result
}

// IsZeroValue checks if a value equals its zero value.
// (this function was improved by AI)
func IsZeroValue[T any](value T) bool {
	return reflect.ValueOf(value).IsZero()
}

// unwrapType removes pointer indirection if present.
// (this function was generated by AI)
func unwrapType(fieldType reflect.Type) reflect.Type {
	if fieldType.Kind() == reflect.Ptr {
		return fieldType.Elem()
	}
	return fieldType
}
