name: Tests
permissions:
  contents: read
on:
  pull_request:

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Install ZSH
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Go version from go.mod
        id: go-version
        run: |
          GO_VERSION=$(grep -E "^go [0-9]+\.[0-9]+" src/main/go/go.mod | awk '{print $2}')
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_OUTPUT
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.GO_VERSION }}

      - name: Install dependencies
        run: |
          cd src/main/go
          go mod download

      - name: Ensure test script is executable
        run: chmod +x test.sh

      - name: Run tests
        run: |
          make test
